import { PageCategory } from './types';

export const progression: PageCategory[] = [
  {
    title: 'West Limegrave',
    subtitle: 'Level: 1~10 Upgrades: 0 ~ +1',
    tasks: [
      'buy-essential-gear',
      'limegrave-west-map-fragment',
      'obtain-wetstone-knife',
      'unlock-torrent',
      'boc-seamster-quest',
      'defeat-nights-cavalry',
      'find-sellen',
      'talk-to-roderika',
      'find-ashes-of-war-merchant',
      'meet-potboy',
      'talk-to-d-hunter',
      'murkwater-cave',
    ],
  },
  {
    title: 'East Limegrave',
    subtitle: 'Level: 5~10 Upgrades: +1 ~ +2',
    tasks: [
      'talk-to-kenneth',
      'get-wondrous',
      'limegrave-east-map-fragment',
      'get-flask-materials-from-erdtree',
      'activate-siofra-river-well',
      'trigger-blaidd',
      'liberate-fort-haight',
      'get-reward-kenneth-haight',
      'complete-summonwater',
      'talk-to-d-hunter-at-roundtable',
      'teleport-bestial-sanctum',
    ],
  },
  {
    title: 'Southern Limegrave & Weeping Peninsula',
    subtitle: 'Level: 20 Upgrades: 3+',
    tasks: [
      'meet-yura',
      'kill-dragon-agheel',
      'obtain-royal-house-scroll',
      'talk-to-irina',
      'defeat-nights-cavalry-2',
      'obtain-memory-slot-1',
      'get-sacred-tears-1',
      'get-flask-materials-erdtree-1',
      'complete-castle-morne',
    ],
  },
  {
    title: 'Roundtable Hold',
    tasks: [
      'head-up-from-stormhill',
      'defeat-margit',
      'visit-roundtable-hold',
      'talk-roundtable-npcs',
      'upgrade-weapons-1',
    ],
  },
  {
    title: 'Stormveil Castle',
    subtitle: 'Level: 30~40 Upgrades: +3 ~ +4',
    tasks: [
      'stormveil-alternate-entrance',
      'ascend-the-castle',
      'defeat-banished-knight',
      'obtain-the-stonesword-key',
      'dispel-fog-enter-gates',
      'locate-nepheli-loux',
      'clear-the-castle-1',
      'fight-the-lion',
      'prepare-for-boss-summon-nepheli',
      'fight-godrick',
      'restore-godricks-great-rune',
    ],
  },
  {
    title: 'Liurnia of the Lakes South',
    subtitle: 'Level: 40~50 Upgrades: +3 ~ +4',
    tasks: [
      'talk-to-boc-the-seamster',
      'meet-sorcerer-thops',
      'obtain-academy-scroll',
      'obtain-fire-monks-prayerbook',
      'get-liurnia-map-fragments',
      'start-ryas-questline',
      'get-cookbooks-and-ritual-pot',
      'meet-patches-get-flask-upgrades',
      'visit-rose-church',
      'find-lakeside-crystal-cave',
      'complete-malefactors-evergoal',
      'loot-sacrificial-twig',
      'obtain-raya-lucaria-academy-key',
    ],
  },
  {
    title: 'Raya Lucaria Academy',
    subtitle: 'Level: 50~60 Upgrades: +4 ~ +6',
    tasks: [
      'acquire-academy-glintstone-key',
      'pickup-several-ashes',
      'obtain-gravity-well-sorcery',
      'get-carian-knight-set',
      'get-conspectus-scroll',
      'get-olivinus-glintstone-crown-and-ritual-pot',
      'defeat-red-wolf-of-radagon',
      'access-secret-radagon-upstairs-area',
      'get-key-golden-seed-glintstone-crown',
      'expore-upper-rooftops',
      'get-imbued-sword-key',
      'loot-scademy-glintstone-key',
      'defeat-moongrum-carian-knight',
      'deal-with-iron-ball',
      'defeat-rennala',
    ],
  },
  {
    title: 'Liurnia of the Lakes East',
    subtitle: 'Level: 50~60 Upgrades: +4 ~ +6',
    tasks: [
      'get-kaiden-sellsword-ashes',
      'get-shabiri-grape-talk-to-hyetta',
      'get-cookbook-staff-highway-lookout',
      'defeat-nights-cavalry-3',
      'defeat-tibia-mariner-2',
      'obtain-dragon-cult-prayerbook',
      'visit-artist-shack',
      'visit-church-of-vows',
      'obtain-flask-upgrades-from-erdtree-2',
      'walking-mausoleum-2',
      'upgrades-raya-lucaria-crystal-tunnel',
      'visit-frenzied-flame-village',
      'spells-from-fringe-tower',
      'unlock-ainsel-river-well',
    ],
  },
  {
    title: 'Ainsel River (Underground)',
    subtitle: 'Level: 50~60 Upgrades: +4 ~ +6',
    tasks: [
      'collect-upgrade-materials-3',
      'find-nomadic-merchant-3',
      'collect-immunizing-horn-charm',
      'defeat-dragonkin-soldier-nokstella',
      'loot-boss-room-3',
    ],
  },
  {
    title: 'Liurnia of the Lakes West',
    subtitle: 'Level: 60~70 Upgrades: +8 ~ +12',
    tasks: [
      'begin-exploration-from-south-to-north',
      'find-fillage-of-the-albinaurics',
      'talk-to-napheli-loux',
      'loot-secret-medallion-key',
      'talk-to-latenna',
      'complete-optional-objectives-2',
      'loot-flask-upgrades-4',
      'visit-thefour-belfries',
      'obtain-map-fragments-4',
      'talk-smithing-master-iji',
      'complete-caria-manor',
      'meet-ranni-and-her-allies',
    ],
  },
  {
    title: 'Siofra River (underground)',
    subtitle: 'Level: 60+ Upgrades: +8 ~ +12',
    tasks: [
      'obtain-map-fragment-5',
      'light-fire-pillars',
      'collect-spells-tailsman-2',
      'collect-key-items',
      'defeat-dragonkin-soldier',
      'obtain-golden-seed-5',
      'unlock-deep-siofra-well',
      'defeat-ancestor-spirit',
    ],
  },
  {
    title: 'Caelid (South)',
    subtitle: 'Level: 60+ Upgrades: +10 ~ +12',
    tasks: [
      'complete-smoldering-church',
      'flask-spirit-upgrades',
      'get-golden-scarab',
      'find-iron-fist-alexander-2',
      'clear-fort-gael',
      'obtain-map-fragment-6',
      'unlock-zone-merchants',
      'defeat-dragon-deathbird',
      'loot-sellia-crystal',
      'meet-gowry-millicent',
      'complete-sellia-tower-sorcery',
      'complete-redmane-castle',
      'defeat-starscourge-radahn',
      'complete-war-dead-catacombs',
      'head-to-altus-plateau',
    ],
  },
  {
    title: 'Nokron, Eternal City & Siofra Aqueduct',
    subtitle: 'Level: 70+ Upgrades: +15 ~ +20',
    tasks: [
      'access-nokron-from-mistwood',
      'loot-ghost-glovewort-picker-bell-1',
      'obtain-larval-tears-2',
      'defeat-mimic-tear',
      'get-to-nights-sacred-ground',
      'loot-black-whetblade-celestial-dew',
      'obtain-fingerslayer-blade',
      'collect-ancestral-infant-head',
      'defeat-regal-ancestor-sprit',
      'enter-siofra-aqueduct',
      'collect-missionary-cookbook-5',
      'trade-twinned-set',
      'defeat-valiant-gargoyle',
    ],
  },
  {
    title: 'Liurnia of the Lakes West 2',
    subtitle: 'Level: 70+ Upgrades: +15 ~ +20',
    tasks: [
      'get-reward-from-ranni-2',
      'carian-study-hall-hidden',
      'obtain-cursemark-of-death',
      'help-iron-fist',
    ],
  },
  {
    title: 'Deeproot Depths',
    subtitle: 'Level: 70+ Upgrades: +15 ~ +20',
    tasks: [
      'defeat-erdtree-avatar',
      'loot-upgrade-materials-deeproot-depths',
      'talk-to-palm-reader',
      'obtain-area-map-deeproot-depths',
      'activate-walking-mausoleum',
      'defeat-crucible-knight-siluria',
      'defeat-fias-champions',
      'talk-to-fia',
      'defeat-lichdragon-fortissax',
    ],
  },
  {
    title: 'Nokstella, Eternal City & Lake of Rot',
    subtitle: 'Level: 80+ Upgrades: +15 ~ +20 (Lake of Rot)',
    tasks: [
      'enter-ainsel-river-main',
      'collect-miniature-ranni',
      'enter-nokstella-eternal-city',
      'collect-key-items-and-spirit-ashes-nokstella',
      'talk-to-miniature-ranni',
      'enter-lake-of-rot',
      'obtain-map-fragment-nokstella',
      'use-the-discarded-palace-key',
      'defeat-dragonkin-soldier',
      'enter-grand-cloister-nokstella',
      'defeat-astel-naturalborn-of-the-void',
    ],
  },
  {
    title: 'Altus Plateau',
    subtitle: 'Level: 60+ Upgrades: +10 ~ +14',
    tasks: [
      'get-access-to-altus-plateau',
      'complete-western-altus-objectives',
      'talk-to-millicent',
      'defeat-tibia-mariner',
      'complete-old-altus-tunnel',
      'complete-shaded-castle',
      'talk-to-millicent-again',
      'complete-golden-lineage-evergaolboc-the-seamster',
      'boc-the-seamster',
      'obtain-zone-map-talk-to-boc-and-corhyn',
      'complete-secong-church-of-marika',
      'get-minord-erdtree-flask-upgrade-complete-valley-objectives',
      'complete-dominula-and-talk-to-millicent',
      'explore-eastern-altus-heights',
      'meet-goldmask-report-to-corhyb',
      'unlock-mt-gelmir-site-of-grace',
    ],
  },
  {
    title: 'Mt Gelmir',
    subtitle: 'Level: 80+ Upgrades: +15 ~ +20',
    tasks: [
      'complete-wyndham-ruins-and-catacombs',
      'collect-golden-seed-2',
      'complete-fort-laeidd',
      'defeat-magma-wyrm',
      'talk-to-iron-fist-2',
      'obtain-memory-stone-comet-azur',
      'complete-gelmir-hero-grave',
      'trigger-patches-event',
      'defeat-fallingstar-beast',
      'loot-golden-seed-map-fragment-3',
      'complete-volcano-manor',
    ],
  },
  {
    title: 'Leyndell, Royal Capital Outskirts',
    subtitle: 'Level: 90 ~ 110 Upgrades: +15 ~ +20',
    tasks: [
      'defeat-tree-sentinel-duo',
      'collect-map-and-golden-seed',
      'complete-sealed-tunnel',
      'collect-golden-seeds-and-fight-margit',
      'complete-events-in-hermit-merchant-shack',
      'loot-flask-upgrades',
      'visit-blackguard-big-boggart',
      'complete-auriza-hero',
      'defeat-draconic-tree-sentinel',
      'complete-legacy-dungeon',
    ],
  },
  {
    title: 'Forbidden Lands',
    subtitle: 'Level: 90+ Upgrades: +20 ~ +24',
    tasks: [
      'enter-leyndell-royal-capital',
      'defeat-nights-cavalry-4',
      'collect-golden-seed',
      'defeat-black-blade-kindred',
      'activate-grand-lift-of-rold',
    ],
  },
  {
    title: 'Mountaintops of the Giants',
    subtitle: 'Level: 90+ Upgrades: +20 ~ +24',
    tasks: [
      'mountaintops-of-the-giants-01',
      'mountaintops-of-the-giants-02',
      'mountaintops-of-the-giants-03',
      'mountaintops-of-the-giants-04',
      'mountaintops-of-the-giants-05',
      'mountaintops-of-the-giants-06',
      'mountaintops-of-the-giants-07',
      'mountaintops-of-the-giants-08',
      'mountaintops-of-the-giants-09',
      'mountaintops-of-the-giants-10',
      'mountaintops-of-the-giants-11',
      'mountaintops-of-the-giants-12',
      'mountaintops-of-the-giants-13',
      'mountaintops-of-the-giants-14',
      'mountaintops-of-the-giants-15',
      'mountaintops-of-the-giants-16',
    ],
  },
  {
    title: 'Consecrated Snowfield',
    subtitle: 'Level: 90+ Upgrades: +20 ~ +24',
    tasks: [
      'consecrated-snowfield-01',
      'consecrated-snowfield-02',
      'consecrated-snowfield-03',
      'consecrated-snowfield-04',
      'consecrated-snowfield-05',
      'consecrated-snowfield-06',
      'consecrated-snowfield-07',
      'consecrated-snowfield-08',
      'consecrated-snowfield-09',
      'consecrated-snowfield-10',
      'consecrated-snowfield-11',
      'consecrated-snowfield-12',
      'consecrated-snowfield-13',
    ],
  },
  {
    title: 'Mohgwyn Palace',
    subtitle: 'Level: 100+ Upgrades: +20 ~ +24',
    tasks: [
      'mohgwyn-palace-01',
      'mohgwyn-palace-02',
      'mohgwyn-palace-03',
      'mohgwyn-palace-04',
      'mohgwyn-palace-05',
    ],
  },
  {
    title: "Miquella's Haligtree",
    subtitle: 'Level: 120+ Upgrades: +25',
    tasks: [
      'miquellas-haligtree-01',
      'miquellas-haligtree-02',
      'miquellas-haligtree-03',
      'miquellas-haligtree-04',
      'miquellas-haligtree-05',
      'miquellas-haligtree-06',
      'miquellas-haligtree-07',
      'miquellas-haligtree-08',
      'miquellas-haligtree-09',
      'miquellas-haligtree-10',
      'miquellas-haligtree-11',
      'miquellas-haligtree-12',
      'miquellas-haligtree-13',
    ],
  },
  {
    title: 'Crumbling Farum Azula',
    subtitle: 'Level: 120+ Upgrades: +25',
    tasks: [
      'crumbling-farum-azula-01',
      'crumbling-farum-azula-02',
      'crumbling-farum-azula-03',
      'crumbling-farum-azula-04',
      'crumbling-farum-azula-05',
      'crumbling-farum-azula-06',
      'crumbling-farum-azula-07',
      'crumbling-farum-azula-08',
      'crumbling-farum-azula-09',
      'crumbling-farum-azula-10',
      'crumbling-farum-azula-11',
    ],
  },
  {
    title: 'Leyndell, Ashen Capital',
    subtitle: 'Level: 150+ Upgrades: +25',
    tasks: [
      'leyndell-ashen-capital-01',
      'leyndell-ashen-capital-02',
      'leyndell-ashen-capital-03',
      'leyndell-ashen-capital-04',
      'leyndell-ashen-capital-05',
      'leyndell-ashen-capital-06',
    ],
  },
  {
    title: 'Subterranean Shunning-Grounds',
    subtitle: 'Level: 150+ Upgrades: +25',
    tasks: [
      'subterranean-shunning-grounds-01',
      'subterranean-shunning-grounds-02',
      'subterranean-shunning-grounds-03',
      'subterranean-shunning-grounds-04',
      'subterranean-shunning-grounds-05',
      'subterranean-shunning-grounds-06',
      'subterranean-shunning-grounds-07',
      'subterranean-shunning-grounds-08',
    ],
  },
  {
    title: 'Endings',
    tasks: [
      'endings-01',
      'endings-02',
      'endings-03',
      'endings-04',
      'endings-05',
      'endings-06',
    ],
  },
];
